### ISSUE TITLE
Crash when intermediate step is null

### ISSUE THREAD

**Issue by steventebrinke** [joe-re/object-dig#8]
When any intermediate step is `null`, the method `dig` crashes, it only works when a key is not present. The Ruby version mentioned in the docs works in both cases, so IMO `dig` should also return `undefined` when an intermediate step is `null`.

**Comment by EricRoos** [comment]
Just ran into this too.

if i do

```
dig(null, 'test');
```
I get an error. My work around is doing something like

```
dig(null || undefined, 'test')
```

This is smelly. May have to change libs.

**Comment by EricRoos** [comment]
@steventebrinke just submitted a pr for this. https://github.com/joe-re/object-dig/pull/9

Hopefully we can get @joe-re to merge :)

**Comment by joe-re** [comment]
@steventebrinke 
This was fixed by @EricRoos.
Thsnks @EricRoos 👍

**Comment by EricRoos** [comment]
Anyway we can get this pushed to npm?

**Comment by joe-re** [comment]
@EricRoos 
sorry, I just published.
please upgrade to 0.1.2
